# Generated by Django 5.1.2 on 2024-10-10 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='name_organizer', max_length=100)),
                ('cpf', models.CharField(db_column='cpf_organizer', max_length=10)),
                ('email', models.EmailField(db_column='email_organizer', max_length=254)),
            ],
            options={
                'db_table': 'Organizer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('date_time', models.DateTimeField(db_column='date_time')),
                ('location', models.CharField(db_column='location', max_length=255)),
                ('max_participants', models.IntegerField(db_column='max_participants')),
                ('participants_count', models.IntegerField(db_column='participants_count', default=0)),
                ('organizer', models.ForeignKey(db_column='organizer', on_delete=django.db.models.deletion.PROTECT, to='teste.organizer')),
            ],
            options={
                'db_table': 'Event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='name_participant', max_length=100)),
                ('cpf', models.CharField(db_column='cpf_participant', max_length=10)),
                ('email', models.EmailField(db_column='email_participant', max_length=254)),
                ('go_event', models.ForeignKey(db_column='go_event', on_delete=django.db.models.deletion.PROTECT, to='teste.event')),
            ],
            options={
                'db_table': 'Participant',
                'managed': True,
            },
        ),
    ]
